# Generated by Django 5.0.6 on 2024-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewlead',
            name='courses',
            field=models.CharField(choices=[('Angular', 'Angular'), ('AWS', 'AWS'), ('AWSWithDevOps', 'AWSWithDevOps'), ('Azure', 'Azure'), ('AzureDevOps', 'AzureDevOps'), ('BusinessAnalyst', 'BusinessAnalyst'), ('CloudOpsMasters', 'CloudOpsMasters'), ('DevOps', 'DevOps'), ('FrontEndAngular', 'FrontEndAngular'), ('FrontEndReact', 'FrontEndReact'), ('FullStackJAVA', 'FullStackJAVA'), ('FullStackMEAN', 'FullStackMEAN'), ('FullStackMERN', 'FullStackMERN'), ('FullstackPython', 'FullstackPython'), ('FullStackReactJAVA', 'FullStackReactJAVA'), ('Java', 'Java'), ('NeedCounselling', 'NeedCounselling'), ('Others', 'Others'), ('PowerBI', 'PowerBI'), ('Python', 'Python'), ('React', 'React'), ('SalesForceAdmin', 'SalesForceAdmin'), ('SalesforceDeveloper', 'SalesforceDeveloper'), ('ServiceNow', 'ServiceNow'), ('AzureDataEngineer', 'AzureDataEngineer'), ('Tableau', 'Tableau'), ('Testing', 'Testing')], default='Angulaar', max_length=20),
        ),
    ]
